version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-2.7
      - test-pypy
jobs:
  test-2.7: &test-template
    docker:
      - image: circleci/python:2.7
    environment:
      CIRCLE_REPOSITORY_URL: https://github.com/abusesa/idiokit
      TOX_VER: py27
    steps:
      - checkout
      - run:
          command: |
            sudo pip install tox
            sudo pip install -r requirements.txt
            mkdir results
      - run:
          command: |
            sudo tox -e flake8 idiokit
      - run:
          command: |
            sudo tox -e $TOX_VER -- idiokit --junitxml=results/$TOX_VER.xml
      - store_test_results:
          path: results
      - store_artifacts:
          path: results
          destination: results
  test-pypy:
    <<: *test-template
    docker:
      - image: pypy:2-6.0
    environment:
      CIRCLE_REPOSITORY_URL: https://github.com/abusesa/idiokit
      TOX_VER: pypy
